version: "3.7"

networks:
  laravelnet:

services: 
  app:
    build:
      context: ./laravelapp
      dockerfile: Dockerfile
    image: laravelapp
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    networks:
      - laravelnet

  db:
    image: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - laravelnet